### ISSUE TITLE
Some texts are black in body

### ISSUE THREAD

**Issue by arifzeeshan** [3raxton/Homesick#1]
Some texts are black making it unreadable-

![screenshot_2019-02-03_00-04-59](https://user-images.githubusercontent.com/26674272/52167864-ba1af180-2747-11e9-9f6a-afb57f662c1b.png)

**Comment by 3raxton** [comment]
Hey @arifzeeshan,

Unfortunately, this is due to the way that the body of emails are designed before being sent. Some have set background colors like white or black, while others are transparent, causing issues like this. 

If you're still using the Homesick theme, I hope that it's helping. Since creating this, I've stopped using Mailspring, and as for this issue, I won't be trying to find a solution. 

Be well!
